name = "LightBSON"
uuid = "a4a7f996-b3a6-4de6-b9db-2fa5f350df41"
authors = ["Christian Rorvik <christian.rorvik@gmail.com>"]
version = "1.3.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"
FNVHash = "5207ad80-27db-4d23-8732-fa0bd339ea89"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
DataStructures = "0.18, 0.19"
Dates = "1"
DecFP = "1"
FNVHash = "0.1"
JSON3 = "1"
Sockets = "1"
StructTypes = "1"
Transducers = "0.4"
UUIDs = "1"
UnsafeArrays = "1"
WeakRefStrings = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
